# Generated by Django 5.0.7 on 2024-07-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Город')),
                ('type_of_region', models.CharField(default='', max_length=8, verbose_name='Тип региона')),
                ('region', models.CharField(default='', max_length=255, verbose_name='Регион')),
                ('timezone', models.CharField(default='', max_length=50, verbose_name='Часовой пояс')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('search_count', models.PositiveBigIntegerField(default=0, verbose_name='Кол-во поисковых запросов')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('name',),
                'unique_together': {('name', 'region', 'latitude', 'longitude')},
            },
        ),
    ]
