# Generated by Django 5.0.7 on 2024-07-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'latitude', 'longitude')},
        ),
    ]
